version: "3.7"
services:

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  the_spacebar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the_spacebar
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80

#    extra_hosts:
#      - "localhost:192.168.1.7"





