version: "3.7"
services:

  mysql:
    image: mysql:5.7
    command: "--sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION --max_allowed_packet=4GB"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: the_spacebar
    ports:
      - "6033:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  the_spacebar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the_spacebar
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/var/www/html
    ports:
      - "9000:80"

#    extra_hosts:
#      - "localhost:192.168.1.7"





